# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build test
    
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Enables pnpm and npm
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    # Installs dependencies
    - name: Install dependencies
      run: pnpm install
    # Creates an envfile with the secrets
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_API_KEY: '${{ secrets.API_KEY }}'
        envkey_API_URL: '${{ secrets.API_URL }}'
        file_name: .env
        directory: ./
    - run: cat .env
    # Builds the site
    - run: pnpm run build
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./build
        destination: ./_site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

